name = "ethernet"
description = "Root crate for ethernet namespace"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/ethernet"
tags = ["network"]
project-files = ["gnat/ethernet.gpr"]

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"

